/* eslint-disable max-lines -- Why: field state, base search, AI generation,
   and cancellation share request guards that need to stay in one hook. */
import { useCallback, useEffect, useRef, useState } from 'react'
import { getConnectionId } from '@/lib/connection-context'
import { useAppStore, type AppState } from '@/store'
import {
  cancelRuntimeGeneratePullRequestFields,
  generateRuntimePullRequestFields,
  type RuntimeGitContext
} from '@/runtime/runtime-git-client'
import {
  getRuntimeRepoBaseRefDefault,
  searchRuntimeRepoBaseRefs
} from '@/runtime/runtime-repo-client'
import {
  isCustomAgentId,
  resolveCommitMessageAgentChoice
} from '../../../../shared/commit-message-agent-spec'
import type { HostedReviewCreationEligibility } from '../../../../shared/hosted-review'
import { normalizeHostedReviewBaseRef } from '../../../../shared/hosted-review-refs'
import {
  DEFAULT_SOURCE_CONTROL_AI_PR_CREATION_DEFAULTS,
  normalizeSourceControlAiSettings
} from '../../../../shared/source-control-ai'
import type { SourceControlAiPrCreationDefaults } from '../../../../shared/source-control-ai-types'

type PullRequestFieldName = 'base' | 'title' | 'body' | 'draft'
export type PullRequestFieldRevisions = Record<PullRequestFieldName, number>
type PullRequestDraftFields = {
  base: string
  title: string
  body: string
  draft: boolean
}

type UseCreatePullRequestDialogFieldsOptions = {
  open: boolean
  repoId: string
  worktreeId: string | null
  worktreePath: string
  branch: string
  eligibility: HostedReviewCreationEligibility | null
  settings: AppState['settings']
  submitting: boolean
  prCreationDefaults?: SourceControlAiPrCreationDefaults
  onBranchChangedByGeneration?: () => Promise<void>
  generation?: {
    generating: boolean
    generateError: string | null
    onGenerate: (fields: PullRequestDraftFields, fieldRevisions: PullRequestFieldRevisions) => void
    onCancelGenerate: () => void
  }
}

type GenerationSeed = {
  requestId: number
  fieldRevisions: PullRequestFieldRevisions
  context: RuntimeGitContext
}

function createInitialPullRequestFieldRevisions(): PullRequestFieldRevisions {
  return {
    base: 0,
    title: 0,
    body: 0,
    draft: 0
  }
}

export function stripBaseRef(ref: string): string {
  return normalizeHostedReviewBaseRef(ref)
}

export function useCreatePullRequestDialogFields({
  open,
  repoId,
  worktreeId,
  worktreePath,
  branch,
  eligibility,
  settings,
  submitting,
  prCreationDefaults,
  onBranchChangedByGeneration,
  generation
}: UseCreatePullRequestDialogFieldsOptions) {
  const normalizedSourceControlAi = normalizeSourceControlAiSettings(
    settings?.sourceControlAi,
    settings?.commitMessageAi
  )
  const sourceControlAi = settings
    ? normalizedSourceControlAi
    : { ...normalizedSourceControlAi, enabled: false }
  const effectiveCommitMessageAgentId = resolveCommitMessageAgentChoice(
    sourceControlAi.agentId,
    settings?.defaultTuiAgent
  )
  const resolvedPrDefaults = {
    ...DEFAULT_SOURCE_CONTROL_AI_PR_CREATION_DEFAULTS,
    ...prCreationDefaults
  }
  const initializedFromEligibilityRef = useRef<string | null>(null)
  const autoGeneratedForKeyRef = useRef<string | null>(null)
  const generateInFlightRef = useRef(false)
  const generationRequestIdRef = useRef(0)
  const generationSeedRef = useRef<GenerationSeed | null>(null)
  const fieldRevisionsRef = useRef<PullRequestFieldRevisions>(
    createInitialPullRequestFieldRevisions()
  )
  const [base, setBase] = useState('')
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const [draft, setDraft] = useState(false)
  const [baseQuery, setBaseQuery] = useState('')
  const [baseResults, setBaseResults] = useState<string[]>([])
  const [baseSearchError, setBaseSearchError] = useState<string | null>(null)
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState<string | null>(null)
  const hasExternalGeneration = Boolean(generation)

  const markFieldDirty = useCallback((field: PullRequestFieldName): void => {
    fieldRevisionsRef.current = {
      ...fieldRevisionsRef.current,
      [field]: fieldRevisionsRef.current[field] + 1
    }
  }, [])

  const setUserBase = useCallback(
    (value: string): void => {
      markFieldDirty('base')
      setBase(value)
    },
    [markFieldDirty]
  )
  const setUserTitle = useCallback(
    (value: string): void => {
      markFieldDirty('title')
      setTitle(value)
    },
    [markFieldDirty]
  )
  const setUserBody = useCallback(
    (value: string): void => {
      markFieldDirty('body')
      setBody(value)
    },
    [markFieldDirty]
  )
  const setUserDraft = useCallback(
    (value: boolean): void => {
      markFieldDirty('draft')
      setDraft(value)
    },
    [markFieldDirty]
  )

  const applyGeneratedFields = useCallback(
    (
      fields: PullRequestDraftFields,
      seedRevisions: PullRequestFieldRevisions
    ): PullRequestDraftFields => {
      const currentRevisions = fieldRevisionsRef.current
      const nextFields = { base, title, body, draft }
      // Why: AI generation runs asynchronously; only fields untouched since
      // the request started are safe to replace with generated output.
      if (currentRevisions.base === seedRevisions.base) {
        nextFields.base = stripBaseRef(fields.base)
        setBase(nextFields.base)
        setBaseQuery('')
        setBaseResults([])
      }
      if (currentRevisions.title === seedRevisions.title) {
        nextFields.title = fields.title
        setTitle(fields.title)
      }
      if (currentRevisions.body === seedRevisions.body) {
        nextFields.body = fields.body
        setBody(fields.body)
      }
      if (currentRevisions.draft === seedRevisions.draft) {
        nextFields.draft = fields.draft
        setDraft(fields.draft)
      }
      return nextFields
    },
    [base, body, draft, title]
  )

  useEffect(() => {
    if (!open) {
      if (!hasExternalGeneration) {
        generationRequestIdRef.current += 1
        if (generateInFlightRef.current) {
          const requestContext = generationSeedRef.current?.context
          if (requestContext?.worktreePath) {
            void cancelRuntimeGeneratePullRequestFields(requestContext)
          }
        }
        generateInFlightRef.current = false
        generationSeedRef.current = null
        initializedFromEligibilityRef.current = null
        autoGeneratedForKeyRef.current = null
        setGenerating(false)
        setGenerateError(null)
      }
      return
    }
    if (!eligibility) {
      return
    }
    const initializationKey = `${repoId}:${worktreeId ?? worktreePath}:${branch}`
    if (initializedFromEligibilityRef.current === initializationKey) {
      return
    }
    // Why: eligibility refreshes while the dialog is open; only seed fields
    // once per branch so late refreshes do not overwrite user edits.
    initializedFromEligibilityRef.current = initializationKey
    autoGeneratedForKeyRef.current = null
    fieldRevisionsRef.current = createInitialPullRequestFieldRevisions()
    const initialBase = eligibility.defaultBaseRef ?? ''
    setBase(stripBaseRef(initialBase))
    setTitle(eligibility.title ?? '')
    setBody(eligibility.body ?? '')
    setDraft(resolvedPrDefaults.draft)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
    setGenerateError(null)
  }, [
    branch,
    eligibility,
    hasExternalGeneration,
    open,
    repoId,
    resolvedPrDefaults.draft,
    worktreeId,
    worktreePath
  ])

  const effectiveGenerating = generation?.generating ?? generating
  const effectiveGenerateError = generation?.generateError ?? generateError

  useEffect(() => {
    if (!open || base) {
      return
    }
    let stale = false
    void getRuntimeRepoBaseRefDefault(settings, repoId)
      .then((result) => {
        if (!stale && result.defaultBaseRef) {
          setBase(stripBaseRef(result.defaultBaseRef))
        }
      })
      .catch(() => undefined)
    return () => {
      stale = true
    }
  }, [base, open, repoId, settings])

  useEffect(() => {
    if (!open || baseQuery.trim().length < 2) {
      setBaseResults([])
      setBaseSearchError(null)
      return
    }
    let stale = false
    const timer = window.setTimeout(() => {
      void searchRuntimeRepoBaseRefs(settings, repoId, baseQuery.trim(), 20)
        .then((results) => {
          if (!stale) {
            setBaseResults(results.map(stripBaseRef))
            setBaseSearchError(null)
          }
        })
        .catch(() => {
          if (!stale) {
            setBaseResults([])
            setBaseSearchError('Branch discovery failed.')
          }
        })
    }, 200)
    return () => {
      stale = true
      window.clearTimeout(timer)
    }
  }, [baseQuery, open, repoId, settings])

  let generateDisabledReason: string | undefined
  if (submitting) {
    generateDisabledReason = 'Create PR in progress...'
  } else if (!sourceControlAi.enabled) {
    generateDisabledReason = 'Enable Source Control AI in Settings -> Git.'
  } else if (!effectiveCommitMessageAgentId) {
    generateDisabledReason = 'Pick an agent in Settings -> Git -> Source Control AI.'
  } else if (isCustomAgentId(effectiveCommitMessageAgentId)) {
    const command = sourceControlAi.customAgentCommand?.trim() ?? ''
    if (!command) {
      generateDisabledReason =
        'Custom command is empty. Add one in Settings -> Git -> Source Control AI.'
    }
  } else if (!base.trim()) {
    generateDisabledReason = 'Choose a base branch before generating.'
  }
  const generateDisabled = !effectiveGenerating && Boolean(generateDisabledReason)

  const handleGenerate = useCallback(async (): Promise<void> => {
    if (!worktreePath || !base.trim() || effectiveGenerating || generateDisabled) {
      return
    }
    if (generation) {
      generation.onGenerate({ base, title, body, draft }, { ...fieldRevisionsRef.current })
      return
    }
    const requestId = generationRequestIdRef.current + 1
    generationRequestIdRef.current = requestId
    const connectionId = getConnectionId(worktreeId) ?? undefined
    const requestContext = {
      settings: useAppStore.getState().settings,
      worktreeId,
      worktreePath,
      connectionId
    }
    const seed = {
      requestId,
      fieldRevisions: { ...fieldRevisionsRef.current },
      context: requestContext
    }
    generationSeedRef.current = seed
    generateInFlightRef.current = true
    setGenerating(true)
    setGenerateError(null)
    try {
      const result = await generateRuntimePullRequestFields(requestContext, {
        base: stripBaseRef(base.trim()),
        title,
        body,
        draft
      })
      if (result.branchChangedByPreparation) {
        await onBranchChangedByGeneration?.()
      }
      const isCurrentRequest = generationRequestIdRef.current === requestId
      if (!isCurrentRequest) {
        return
      }
      if (!result.success) {
        if (result.canceled) {
          setGenerateError(null)
          return
        }
        setGenerateError(result.error)
        return
      }

      const currentSeed = generationSeedRef.current
      if (!currentSeed || currentSeed.requestId !== requestId) {
        return
      }
      applyGeneratedFields(result.fields, currentSeed.fieldRevisions)
      useAppStore.getState().recordFeatureInteraction('ai-pr-generation')
      setGenerateError(null)
    } catch (error) {
      if (generationRequestIdRef.current !== requestId) {
        return
      }
      setGenerateError(
        error instanceof Error ? error.message : 'Failed to generate pull request details'
      )
    } finally {
      if (generationRequestIdRef.current === requestId) {
        generateInFlightRef.current = false
        generationSeedRef.current = null
        setGenerating(false)
      }
    }
  }, [
    base,
    body,
    draft,
    effectiveGenerating,
    applyGeneratedFields,
    generation,
    generateDisabled,
    onBranchChangedByGeneration,
    title,
    worktreeId,
    worktreePath
  ])

  const handleCancelGenerate = useCallback((): void => {
    if (generation) {
      generation.onCancelGenerate()
      return
    }
    const requestContext = generationSeedRef.current?.context
    if (!requestContext?.worktreePath || !generateInFlightRef.current) {
      return
    }
    generationRequestIdRef.current += 1
    generateInFlightRef.current = false
    generationSeedRef.current = null
    setGenerating(false)
    setGenerateError(null)
    void cancelRuntimeGeneratePullRequestFields(requestContext)
  }, [generation])

  useEffect(() => {
    if (
      !open ||
      !resolvedPrDefaults.generateDetailsOnOpen ||
      !initializedFromEligibilityRef.current ||
      autoGeneratedForKeyRef.current === initializedFromEligibilityRef.current ||
      generateDisabled ||
      effectiveGenerating ||
      !base.trim()
    ) {
      return
    }
    autoGeneratedForKeyRef.current = initializedFromEligibilityRef.current
    void handleGenerate()
  }, [
    base,
    effectiveGenerating,
    generateDisabled,
    handleGenerate,
    open,
    resolvedPrDefaults.generateDetailsOnOpen
  ])

  return {
    aiGenerationEnabled: sourceControlAi.enabled === true,
    base,
    setBase: setUserBase,
    title,
    setTitle: setUserTitle,
    body,
    setBody: setUserBody,
    draft,
    setDraft: setUserDraft,
    fieldRevisions: fieldRevisionsRef.current,
    applyGeneratedFields,
    baseQuery,
    setBaseQuery,
    baseResults,
    setBaseResults,
    baseSearchError,
    generating: effectiveGenerating,
    generateError: effectiveGenerateError,
    generateDisabled,
    generateDisabledReason,
    handleGenerate,
    handleCancelGenerate
  }
}
